Repository chiyadev/genshin-schedule, pull requests merged in 2021-12, with the labels that each got.

#104 Update database for 2.3
  web/assets/game/Cinnabar Spindle.png
  web/assets/game/Gorou.png
  web/assets/game/Husk of Opulent Dreams.png
  web/assets/game/Itto.png
  web/assets/game/Ocean-Hued Clam.png
  web/assets/game/Redhorn Stonethresher.png
  web/assets/game/Riftborn Regalia.png
  web/assets/index.ts
  web/components/ChangelogModal.tsx
  web/components/Customize/LeakedWarning.tsx
  web/db/artifacts.ts
  web/db/characterMaterials.ts
  web/db/characters.ts
  web/db/commonMaterials.ts
  web/db/domainCategories.ts
  web/db/domainDropSets.ts
  web/db/domains.ts
  web/db/regions.ts
  web/db/weapons.ts
  web/langs/en_US.json
  web/langs/en_US.pot
  web/pages/customize/characters/[name].tsx
  web/pages/customize/weapons/[name].tsx
Labels: enhancement, database

#105 Update database for 2.4 leaks
  web/assets/game/Calamity Queller.png
  web/assets/game/Dragonheir's False Fin.png
  web/assets/game/Shenhe.png
  web/assets/game/Yun Jin.png
  web/assets/index.ts
  web/components/ChangelogModal.tsx
  web/components/Customize/CharacterInfo/CommonMaterialDisplay.tsx
  web/components/DropLabel.tsx
  web/db/characterMaterials.ts
  web/db/characters.ts
  web/db/regions.ts
  web/db/weapons.ts
  web/langs/en_US.json
  web/langs/en_US.pot
Labels: enhancement, database

#106 Add support for custom resin buttons
  web/components/ChangelogModal.tsx
  web/components/Customize/SettingsList/ResinCalcButtonInput.tsx
  web/components/Customize/SettingsList/index.tsx
  web/components/Home/Resin/SideButtons.tsx
  web/components/Home/Resin/Subtractor.tsx
  web/components/Home/Resin/index.tsx
  web/components/ShortcutHelp.tsx
  web/langs/en_US.json
  web/langs/en_US.pot
  web/utils/config.ts
Labels: enhancement

#107 Remove accuracy warning for Gorou, Itto, Redhorn Stonethresher
  web/components/ChangelogModal.tsx
  web/db/characters.ts
  web/db/weapons.ts
  web/langs/en_US.pot
Labels: enhancement, database

#108 Improve calculator buttons so they are always shown on any touch-based device
  web/components/ChangelogModal.tsx
  web/components/Home/RealmCurrency/index.tsx
  web/components/Home/Resin/index.tsx
  web/langs/en_US.pot
Labels: enhancement

#109 Fix item arrays for some bosses
  web/db/domainDropSets.ts
Labels: bug, database
