Repository chiyadev/genshin-schedule, pull requests merged in 2021-01, with the labels that each got.

#25 Add tracking for Local Specialities
  web/assets/game/Blackcliff Agate.png
  web/assets/game/Blackcliff Longsword.png
  web/assets/game/Blackcliff Pole.png
  web/assets/game/Blackcliff Slasher.png
  web/assets/game/Prototype Amber.png
  web/assets/game/Prototype Archaic.png
  web/assets/game/Prototype Starglitter.png
  web/assets/index.ts
  web/components/Map/TaskMarker/IconPage/search.ts
  web/db/characters.ts
  web/db/commonMaterials.ts
  web/db/weapons.tsx
Labels: enhancement

#39 Add character, weapon and artifact filter buttons to the domain list
  web/assets/game/WhiteAnemo.png
  web/assets/game/WhiteArtifact.png
  web/assets/game/WhiteWeapon.png
  web/assets/index.ts
  web/components/ChangelogModal.tsx
  web/components/Customize/ArtifactList/index.tsx
  web/components/Customize/CharacterList/index.tsx
  web/components/Customize/WeaponList/index.tsx
  web/components/Home/DomainView/FilterButtons.tsx
  web/components/Home/DomainView/index.tsx
  web/components/Home/Tasks/SearchButton.tsx
  web/utils/configs.ts
  web/utils/index.ts
Labels: enhancement

#37 Add Weekly Talent Materials
  web/assets/game/Dvalin's Claw.png
  web/assets/game/Dvalin's Plume.png
  web/assets/game/Dvalin's Sigh.png
  web/assets/game/Ring of Boreas.png
  web/assets/game/Shadow of the Warrior.png
  web/assets/game/Shard of a Foul Legacy.png
  web/assets/game/Spirit Locket of Boreas.png
  web/assets/game/Tail of Boreas.png
  web/assets/game/Tusk of Monoceros Caeli.png
  web/assets/index.ts
  web/components/ChangelogModal.tsx
  web/components/Customize/CharacterInfo/MaterialDisplay.tsx
  web/components/Customize/CharacterInfo/Toggle.tsx
  web/components/Customize/CharacterList/Icon.tsx
  web/components/Home/DomainView/index.tsx
  web/db/characters.ts
  web/db/domainDropSets.ts
  web/db/talentMaterials.ts
  web/pages/characters/[name].tsx
  web/utils/configs.ts
Labels: enhancement

#40 Add 'Enter the Golden House' Trounce Domain
  web/db/domainCategories.ts
  web/db/domainDropSets.ts
  web/db/domains.ts
  web/db/regions.ts
Labels: bug, database

#41 Add Portable Waypoint
  web/assets/game/Portable Waypoint.png
  web/assets/index.ts
  web/components/Map/TaskMarker/IconPage/search.ts
Labels: enhancement, tasks

#44 Implement 'useFilteredTasks' to fix search function
  web/components/TaskListCard/index.tsx
Labels: bug, regression, tasks
