Repository chiyadev/genshin-schedule, pull requests merged in 2021-05, with the labels that each got.

#61 Register Service Worker to make the website installable as PWA
  web/components/ChangelogModal.tsx
  web/pages/_app.tsx
  web/public/manifest.json
  web/public/sw.js
Labels: enhancement

#63 Add realm currency calculator
  web/assets/game/Realm Currency.png
  web/assets/index.ts
  web/components/AutoSizeInput.tsx
  web/components/ChangelogModal.tsx
  web/components/Home/RealmCurrency/ClearButton.tsx
  web/components/Home/RealmCurrency/CurrencyInput.tsx
  web/components/Home/RealmCurrency/EnergyInput.tsx
  web/components/Home/RealmCurrency/Estimator.tsx
  web/components/Home/RealmCurrency/TrustRankInput.tsx
  web/components/Home/RealmCurrency/index.tsx
  web/components/Home/Resin/EstimatorByResin.tsx
  web/components/Home/Resin/EstimatorByTime.tsx
  web/components/Home/Resin/index.tsx
  web/components/Map/TaskMarker/IconPage/search.ts
  web/db/realms.ts
  web/langs/en-US.json
  web/pages/home/index.tsx
  web/utils/config.ts
  web/utils/dom.ts
Labels: enhancement

#66 Fix task done / to-do text swapped
  web/components/Map/TaskLayer/DoneButton.tsx
Labels: bug, high-priority

#77 Update langs/README.md
  web/langs/README.md
Labels: documentation, i18n

#71 Realm currency steps
  web/components/ChangelogModal.tsx
  web/components/Home/RealmCurrency/Estimator.tsx
  web/components/Home/RealmCurrency/EstimatorByCurrency.tsx
  web/components/Home/RealmCurrency/EstimatorByTime.tsx
  web/components/Home/RealmCurrency/index.tsx
  web/langs/en_US.pot
Labels: enhancement

#86 Fix incorrect weapons and add missing weapons
  web/assets/game/Alley Hunter.png
  web/assets/game/Blackcliff Warbow.png
  web/assets/game/Favonius Lance.png
  web/assets/game/Royal Bow.png
  web/assets/game/Royal Greatsword.png
  web/assets/game/Royal Longsword.png
  web/assets/game/Royal Spear.png
  web/assets/game/The Unforged.png
  web/assets/game/Vortex Vanquisher.png
  web/assets/game/Wine and Song.png
  web/assets/index.ts
  web/components/ChangelogModal.tsx
  web/db/weapons.ts
  web/langs/en_US.pot
Labels: bug, database

#87 Use next.js scrollRestoration experimental flag
  web/components/ChangelogModal.tsx
  web/langs/en_US.pot
  web/next.config.js
  web/pages/_app.tsx
  web/utils/scrollPreserver.ts
Labels: regression
